apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
spec:
  project: default
  source:
    chart: jenkins
    repoURL: https://charts.jenkins.io
    # targetRevision: 1.16.1
    helm:
      releaseName: jenkins
  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins