apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
spec:
  project: default
  source:
    chart: jenkins
    repoURL: https://charts.jenkins.io
    targetRevision: 3.11.3
    helm:
      releaseName: jenkins
      values: |
        controler:
          installPlugins:
          - kubernetes:1.31.3
          - workflow-aggregator:2.6
          - git:4.10.2
          - configuration-as-code:1.55.1
          - kubernetes-credentials-provider:0.20
  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins